- name: Install common tools
  yum: name={{ item }} state=present
  with_items:
    - dstat
    - lsof
    - bash-completion
    - time
    - tmux
    - lvm2-sysvinit
  when: ansible_lsb.id=="CentOS" and ansible_lsb.major_release=="7"

