- name: format new image volumee
  filesystem:
   dev: "{{ image_device }}"
   fstype: xfs
  when: image_device is defined
  become: True

- name: mount image device
  mount:
    name: /var/lib/pb
    src: "{{ image_device }}"
    state: mounted
    fstype: xfs
  when: image_device is defined
  become: True

- name: set permissions on image volume mount
  file:
    name: /var/lib/pb
    state: directory
    owner: cloud-user
    group: cloud-user
  when: image_device is defined
  become: True

