- name: format new image volumee
   dev: "{{ image_device }}"
   fstype: xfs
   resizefs: yes
  when: image_device is defined
  become: True

- name: mount image device
  mount:
    name: /var/lib/pb
    src: "{{ image_device }}"
    state: mounted
    fstype: xfs
  when: image_device is defined
  become: True

- name: set permissions on image volume mount
  file:
    name: /var/lib/pb
    state: directory
    owner: cloud-user
    group: cloud-user
  when: image_device is defined
  become: True

##- name: format /var/lib/docker device
#   dev: "{{ lib_docker_device }}"
#   fstype: xfs
#   resizefs: yes
#  when: lib_docker_device is defined
#  become: True

#- name: mount device to /var/lib/docker
#  mount:
#    name: /var/lib/pb
#    src: "{{ lib_docker_device }}"
#    state: mounted
#    fstype: xfs
#  when: lib_docker_device is defined
#become: True

