---
- include: roles/docker_host/main.yml

- hosts:
    - www
    - worker
    - proxy
  sudo: True
  roles:
      - common

- hosts: www
  sudo: True
  roles:
      - www

- hosts: worker
  sudo: True
  roles:
      - worker

- hosts: proxy
  sudo: True
  roles:
      - proxy
