---
- hosts:
    - localhost
  sudo: True
  roles:
    - docker_host

- hosts:
    - localhost
  sudo: True
  roles:
    - single_server_with_docker
  vars:
    - image_name: ubuntu_with_ssh

- hosts:
    - www
    - worker
    - proxy
  sudo: True
  roles:
      - cloud_user_with_sudo
      - common

- hosts: www
  sudo: True
  roles:
      - www

- hosts: worker
  sudo: True
  roles:
      - worker

- hosts: proxy
  sudo: True
  roles:
      - proxy
