---
- hosts:
    - docker_host
  become: True
  roles:
    - docker_host

  tasks:
  - assert:
      that:
        - extra_variables_loaded is defined 
      msg: "Did you forget to give variables file?"

- hosts:
    - docker_host
  become: True
  roles:
    - single_server_with_docker
  vars:
    - image_name: ubuntu_with_ssh
    - application_secret_key: "{{ lookup('password',
                                '~/..pb_application_secret_key length=32')}}"
- hosts:
    - api
    - worker
    - frontend
  become: True
  roles:
      - cloud_user_with_sudo
      - common
  vars:
    - application_secret_key: "{{ lookup('password',
                                '~/..pb_application_secret_key length=32')}}"

- hosts: frontend
  become: True
  roles:
      - frontend
  vars:
    - application_secret_key: "{{ lookup('password',
                                '~/..pb_application_secret_key length=32')}}"

- hosts: api
  become: True
  roles:
      - api
      - reload_on_git_update
  vars:
    - application_secret_key: "{{ lookup('password',
                                '~/..pb_application_secret_key length=32')}}"
    - git_status: "{{hostvars[docker_host_inventory_hostname]['git_status']|default(False)}}"
    - programs:
      - gunicorn_app
      - gunicorn_worker_app

- hosts: worker
  become: True
  roles:
      - worker
      - reload_on_git_update
  vars:
    - application_secret_key: "{{ lookup('password',
                                '~/..pb_application_secret_key length=32')}}"
    - git_status: "{{hostvars[docker_host_inventory_hostname]['git_status']|default(False)}}"
    - programs:
      - "{{ application_name }}_workers:"
      - "{{ application_name }}-system-worker"
- hosts: sso
  become: True
  roles:
      - sso
      - cloud_user_with_sudo
  vars:
    - application_secret_key: "{{ lookup('password',
                                '~/..pb_application_secret_key length=32')}}"
