---
- name: Prepare docker host VM
  hosts: docker_host
  sudo: yes
  tasks:
    - name: update key apt repositories
      template:
        src=roles/common/templates/etc/apt/sources.list.j2
        dest=/etc/apt/sources.list
        backup=yes

    - name: add docker repo key
      apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

    - name: add docker repo
      apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

    - name: Install packages
      apt: name={{ item }} state=present
      with_items:
        - lxc-docker
        - python-pip
        - dstat
        - tmux
        - git
        - build-essential
        - python-dev

    - name: Install docker-py from pip (required by ansible, not available for Trusty as apt package)
      pip: name={{ item }}
      with_items:
        - docker-py
        - ansible

    - name: Add cloud-user to docker group and create ssh key
      user:
        name=cloud-user
        append=yes
        groups=docker
        generate_ssh_key=yes

    - name: Fetch application from Github
      git:
        repo=https://github.com/CSC-IT-Center-for-Science/pouta-blueprints.git
        dest=/opt/pouta-blueprints
