---

# this is the address nginx etc. will listen to, provide this when the ip needs to be static for eg. in production
# public_ipv4: 192.168.1.100

# this is the domain name
# domain_name: "pebbles-test.internal"

deploy_mode: docker

#affects the server that serves in API
server_type: prod

application_debug_logging: false

#safest to point to a tagged version in production
git_version: "refactor/remove_db_dependency_from_configs#607"


# it's not required to have SSO integration
use_sso: False
#shibboleth_entity_id: "https:/notebooks.example.org"
#shibboleth_discovery_url: "https://federation.example.org/shibboleth/WAYF"
#shibboleth_metadata_url: "https://federation.example.org/metadata/metadata.xml"
#shibboleth_support_contact: "help@example.org"
#

# if this is not defined the playbook will assume you messed up
extra_variables_loaded: True

# sender_email: 'sender@example.org'
# mail_server: 'smtp.example.org'
# mail_suppress_send = True
#mail_use_tls: False

#fake_provisioning: False
#skip_task_queue: False
# write_provisioning_logs: True

instance_name_prefix: 'pb-'
# default_quota: '{{ default_quota }}'

installation_name: 'Pebbles-Test'
installation_description: 'Pebbles test instance'
# brand_image: ''
