---

- name: Fetch application from Github
  git: repo=https://github.com/CSC-IT-Center-for-Science/resource-cloud.git dest={{ application_path }}
  when: deploy_mode != "devel"

- name: Link shared directory to application_path
  file: src=/vagrant dest={{ application_path }} state=link
  when: deploy_mode == "devel"

- name: Install dependencies from requirements.txt
  pip: requirements={{ application_path }}/requirements.txt virtualenv={{ virtualenv_path }}

- name: Copy application configuration
  template: src=app_config.j2
            dest={{ application_config }}

