- name: install dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=36000
  with_items:
    - git
    - python
    - python-pip
    - python-dev
    - python-virtualenv
    - nginx
    - supervisor
    - rabbitmq-server

- include: create_users_and_groups.yml
- include: setup_virtualenv.yml
- include: setup_runtime_directories.yml
- include: fetch_application.yml
- include: setup_supervisor.yml
- include: setup_nginx.yml 
