- name: update apt repository to {{ apt_repository_url }}
  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu trusty main' state=absent
  apt_repository: repo='deb-src http://archive.ubuntu.com/ubuntu trusty main' state=absent
  apt_repository: repo='deb {{ apt_repository_url }} trusty main' state=present
  apt_repository: repo='deb-src {{ apt_repository_url }} trusty main' state=present

- name: install dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=36000
  with_items:
    - git
    - python
    - python-pip
    - python-dev
    - python-virtualenv
    - nginx
    - supervisor
    - rabbitmq-server

- include: create_users_and_groups.yml
- include: setup_virtualenv.yml
- include: setup_runtime_directories.yml
- include: fetch_application.yml
- include: setup_supervisor.yml
- include: setup_nginx.yml 
