---
- name: Create the Gunicorn script file
  template: src=gunicorn_start.j2
            dest={{ virtualenv_path }}/bin/gunicorn_start
            owner={{ application_user }}
            group={{ application_group }}
            mode=0755
            backup=yes
  when: server_type == "prod"

- name: Create the development server script file
  template: src=devserver_start.j2
            dest={{ virtualenv_path }}/bin/devserver_start
            owner={{ application_user }}
            group={{ application_group }}
            mode=0755
            backup=yes
  when: server_type == "devel"
