---
- name: Create the Gunicorn script file
  template: src=gunicorn_start.j2
            dest={{ virtualenv_path }}/bin/gunicorn_start
            owner={{ application_user }}
            group={{ application_group }}
            mode=0755
            backup=yes

- name: Copy application configuration
  template: src=app_config.j2
            dest={{ application_config }}
