---
- name: Create the Gunicorn script file
  template: src=gunicorn_start.j2
            dest={{ virtualenv_path }}/bin/gunicorn_start
            owner={{ application_user }}
            group={{ application_group }}
            mode=0755
            backup=yes

- name: Create the application log directory
  file: path={{ application_log_dir }}
        owner={{ application_user }}
        group={{ application_group }}
        mode=0774
        state=directory

- name: Create the application log file
  command: touch {{ application_log_file }}
           creates={{ application_log_file }}

- name: Create runtime directory
  file:
    dest={{ runtime_path }} 
    mode=775 state=directory 
    owner={{ application_user }} 
    group={{ application_group }}

- name: Set permission to the application log file
  file: path={{ application_log_file }}
        owner={{ application_user }}
        group={{ application_group }}
        mode=0664
        state=file
