---
- name: Create the Supervisor config file for www
  template: src=etc/supervisor/supervisor_config.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-www.conf
            backup=yes

- name: Re-read the Supervisor config files
  command: supervisorctl reread

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update
