apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
spec:
  serviceName: worker
  selector:
    matchLabels:
      name: worker
  replicas: {{ .Values.workerReplicas }}
  template:
    metadata:
      labels:
        name: worker
    spec:
      serviceAccount: worker
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: wait-for-api
          image: {{ .Values.workerImage }}
          imagePullPolicy: {{ .Values.workerImagePullPolicy }}
          command:
            - bash
            - -c
            - until curl -s -m 1 -o /dev/null api:8080/api/v1/config; do echo waiting for api; sleep 1; done
      containers:
        - name: worker
          image: {{ .Values.workerImage }}
          imagePullPolicy: {{ .Values.workerImagePullPolicy }}
          command:
            - python
            - pebbles/worker/main.py
          env:
            - name: PYTHONPATH
              value: /opt/app-root/src
            - name: PB_INTERNAL_API_BASE_URL
              value: http://api:8080/api/v1
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pebbles
                  key: pb-secret-key
            {{- if .Values.ingressAppDomain }}
            - name: INGRESS_APP_DOMAIN
              value: {{ .Values.ingressAppDomain }}
            {{- end }}
            {{- if .Values.remoteDebugServerWorker }}
            - name: REMOTE_DEBUG_SERVER
              value: {{ .Values.remoteDebugServerWorker }}
            {{- end }}
          {{- if .Values.mountHostSrc }}
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: src
          {{- end }}
      {{- if .Values.mountHostSrc }}
      volumes:
        - name: src
          hostPath:
            path: {{ .Values.mountHostSrc }}
            type: Directory
      {{- end }}
