---
heat_template_version: 2015-10-15

parameters:
  env_name:
    description: >
      A name for the Pebbles environment to be used for naming resources.
    type: string
  name_suffix:
    description: >
      A name suffix for this security group.
    type: string
  vol_size:
    description: >
      Rules for this security group.
    type: string

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      name:
        str_replace:
          template: env_name-name_suffix
          params:
            env_name: { get_param: env_name }
            name_suffix: { get_param: name_suffix }
        size: { get_param: vol_size }

outputs:
  OS::stack_id:
    value: { get_resource: volume }