- name: restart docker
  service: name=docker state=restarted

# if we restart iptables, dockerd needs to be restarted, too
- name: restart iptables
  service: name={{ item }} state=restarted
  with_items:
    - iptables
    - docker
  when: ansible_lsb.id=="CentOS"

- name: restart iptables-persistent
  service: name={{ item }} state=restarted
  with_items:
    - iptables-persistent
    - docker
  when: ansible_lsb.id=="Ubuntu"
