---
- name: Create the Supervisor config file for user tasks
  template: src=etc/supervisor/conf.d/worker.conf.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-worker.conf
            backup=yes

- name: Create the Supervisor config file for system tasks
  template: src=etc/supervisor/conf.d/system-worker.conf.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-system-worker.conf
            backup=yes

- name: Re-read the Supervisor config files
  command: supervisorctl reread

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update

- name: Restart Supervisor
  command: supervisorctl restart {{ application_name }}-worker
