- name: Generate CA key and certificate
  command:
    openssl req -new -nodes -x509 -subj "/C=FI/ST=SouthernFinland/L=Helsinki/O=IT/CN={{ domain }}" -days 3650 -keyout {{ runtime_path }}/ca_key.pem -out {{ runtime_path }}/ca_cert.pem
    creates={{ runtime_path }}/ca_cert.pem

- name: Generate client key and certificate request
  command:
    openssl req -new -nodes -subj '/CN=client' -keyout {{ runtime_path }}/client_key.pem -out {{ runtime_path }}/client.csr
    creates={{ runtime_path }}/client_key.pem

- name: Generate signing config
  lineinfile:
    dest={{ runtime_path }}/extfile.cnf
    line="extendedKeyUsage = clientAuth"
    create=yes

- name: Sign client certificate
  command:
    openssl x509 -req -days 3650 -in {{ runtime_path }}/client.csr -CA {{ runtime_path }}/ca_cert.pem -CAkey {{ runtime_path }}/ca_key.pem -CAcreateserial -out {{ runtime_path }}/client_cert.pem -extfile {{ runtime_path }}/extfile.cnf
    creates={{ runtime_path }}/client_cert.pem

- name: Generate a self signed certificate for docker servers
  command:
    openssl req -new -nodes -subj '/CN=server' -keyout {{ runtime_path }}/server_key.pem -out {{ runtime_path }}/server.csr
    creates={{ runtime_path }}/server_key.pem

- name: Sign server certificate
  command:
    openssl x509 -req -days 3650 -in {{ runtime_path }}/server.csr -CA {{ runtime_path }}/ca_cert.pem -CAkey {{ runtime_path }}/ca_key.pem -CAcreateserial -out {{ runtime_path }}/server_cert.pem
    creates={{ runtime_path }}/server_cert.pem
