---
- name: install pouta-virtualcluster package dependencies
  apt: name={{ item }} state=present
  with_items:
      - python-openstackclient

- name: Make base directory for pouta-virtualcluster
  file: name={{ pvc_install_dir }} state=directory

- name: Checkout pouta-virtualcluster from GitHub
  git: repo=https://github.com/CSC-IT-Center-for-Science/pouta-virtualcluster.git dest={{ pvc_install_dir }}/


