---

- name: Fetch application from Github
  git: repo=https://github.com/CSC-IT-Center-for-Science/pouta-blueprints.git dest={{ application_path }}
  when: deploy_mode != "devel"

- name: Link shared directory content to application_path
  file: src={{ shared_folder_path }} dest={{ application_path }} state=link
  when: deploy_mode == "devel"

- name: Install dependencies from requirements.txt
  pip: requirements={{ application_path }}/requirements.txt virtualenv={{ virtualenv_path }}

- name: Install infrastructural dependencies from PyPI
  pip: name={{ item }} virtualenv={{ virtualenv_path }}
  with_items:
      - gunicorn
