- name: Tools for debugging installation (Centos)
  yum: name={{ item }} state=present
  with_items:
    - dstat
    - lsof
    - bash-completion
    - time
  when: ansible_lsb.id=="CentOS"

- name: Install dependencies (CentOS)
  yum: name={{ item }} state=present
  with_items:
    - git
    - python
    - python-pip
    - python-dev
    - libffi-devel
    - openssl-devel
    - python-virtualenv
    - supervisor
  when: ansible_lsb.id=="CentOS"

- include: create_users_and_groups.yml
- include: setup_virtualenv.yml
- include: fetch_application.yml
- include: setup_supervisor.yml
- include: setup_runtime_directories.yml
